#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

echo "Configuring Firebase in src/analytics/firebase.ts..."

# Create the directory if it doesn't exist
mkdir -p src/analytics

# Write the firebase.ts file using environment variables for Firebase config
# These environment variables (FB_API_KEY, FB_AUTH_DOMAIN, etc.)
# are expected to be set by the GitHub Actions workflow step that calls this script.

cat <<EOF > src/analytics/firebase.ts
// This file is automatically generated by a script during the build process.
// Do not edit it manually, as your changes will be overwritten.
import { initializeApp } from "firebase/app";
// import { getAnalytics } from "firebase/analytics"; // Uncomment if you use analytics

const firebaseConfig = {
  apiKey: "${FB_API_KEY}",
  authDomain: "${FB_AUTH_DOMAIN}",
  projectId: "${FB_PROJECT_ID}",
  storageBucket: "${FB_STORAGE_BUCKET}",
  messagingSenderId: "${FB_MESSAGING_SENDER_ID}",
  appId: "${FB_APP_ID}",
  measurementId: "${FB_MEASUREMENT_ID}",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
// const analytics = getAnalytics(app); // Uncomment if you use analytics

export default app; // Or export { app, analytics };
EOF

echo "src/analytics/firebase.ts configured successfully by script."
